name: Build Docker Image

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master repo
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          secrets: |
            "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
            "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            "DB=${{ secrets.DB }}"
            "DB_HOST=${{ secrets.DB_HOST }}"
            "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
            "DB_USER=${{ secrets.DB_USER }}"
            "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
            "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}"
            "ORIGIN=${{ secrets.ORIGIN }}"
            "SECRET=${{ secrets.SECRET }}"
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            kieranlewin/axilier-api:${{env.RELEASE_VERSION}}
            kieranlewin/axilier-api:latest
